pipeline {
   agent any
    environment {
      RELEASE='20.04'
    }
   stages {
      stage('Build') {
            environment {
               LOG_LEVEL='INFO'
            }
            steps {
               echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
               withCredentials([string(credentialsId: 'testsecret',variable: 'TESTSECRET')]){

                   sh '''
                        chmod +x ./test.sh
                        ./test.sh
                   '''

               }
            }
        }
        stage('Test') {
            steps {
               echo "Testing release ${RELEASE}"
               writeFile file: 'test-results.txt', text: 'passed'
                        
            }
        }
   }
   post {
      success {
         archiveArtifacts 'test-results.txt'
         slackSend channel: '#general',
                   message: "Release ${env.RELEASE}, success: ${currentBuild.fullDisplayName}."
         
      }
      failure {
          slackSend channel: '#general',
                   message: "Release ${env.RELEASE}, failed: ${currentBuild.fullDisplayName}."
      }
   }
}