def image
def testVar="Hello World"
pipeline {
    agent any
    
    
    
    
    stages {
        stage('Build Image'){
            steps {
                
                script {
                    image = docker.build("meyysevugan/testimages:1.0","docker_image_build")
                }
            }
        }
        stage('Test Global Var'){
            steps{
                
                sh "echo ${testVar}"
            }
        }

        stage('Smoke Test'){
            steps {
                script {
                    println "Inside the script block: ${testVar}"
                    container = image.run()
                    container.stop()
                }
            }
        }

        stage('Image Push'){
            steps {
                script {
                    docker.withRegistry('', 'docker-creds'){
                        image.push()
                    }
                }
            }
        }
    }
}

