pipeline {
    agent any
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    parameters{
        booleanParam(name: 'RC', defaultValue: false,description: 'Chooses wether we need to generate RC candidate' )
    }
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                 
                '''
            }
        }
        stage ('Checkout Code'){
            steps{
            git url: 'https://github.com/meyysevugan/jgsu-spring-petclinic.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
              echo "Building version: ${VERSION} with suffix: ${VERSION_RC}"
              sh 'mvnw clean build'
            
            }
        }
        stage('Unit Test') {
            steps {
              sh 'mvnw clean test'
            }
        }
        stage('Package') {
            when {
                expression {return params.RC }
            }
            steps {
                sh 'mvnw clean package'
                archiveArtifacts './target/*.jar'
            }
        }
    }
}