pipeline {
    agent {
        docker {
            image 'node:16-alpine'
        }
    }
    
    
    stages {
        stage('Test Tools'){
            steps {
                
                echo "Hello world"
            }
        }
    }
}

