pipeline {
    agent {
        docker {
            image 'node:latest'
        }
    }
    
    
    
    stages {
        stage('Test Tools'){
            steps {
                
                sh 'docker image ls'
            }
        }
    }
}

